<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit30260c7069db57dc85d078d75ddef1a6
{
    public static $files = array (
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '7b11c4dc42b3b3023073cb14e519683c' => __DIR__ . '/..' . '/ralouphie/getallheaders/src/getallheaders.php',
        '320cde22f66dd4f5d3fd621d3e88b98f' => __DIR__ . '/..' . '/symfony/polyfill-ctype/bootstrap.php',
        '0ef2dab037384f92bdddd868ec78c76a' => __DIR__ . '/..' . '/daverandom/exceptional-json/src/functions.php',
        '987d5bfa26b051e8dda7e68dc3c9857b' => __DIR__ . '/..' . '/roave/doctrine-simplecache/namespace-bc-aliases.php',
    );

    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\Ctype\\' => 23,
            'Symfony\\Contracts\\' => 18,
            'Symfony\\Component\\Filesystem\\' => 29,
        ),
        'R' => 
        array (
            'Roave\\DoctrineSimpleCache\\' => 26,
        ),
        'P' => 
        array (
            'Psr\\SimpleCache\\' => 16,
        ),
        'E' => 
        array (
            'ExceptionalJSON\\' => 16,
        ),
        'D' => 
        array (
            'Doctrine\\Common\\Cache\\' => 22,
        ),
        'B' => 
        array (
            'BrowscapPHP\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\Ctype\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-ctype',
        ),
        'Symfony\\Contracts\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/contracts',
        ),
        'Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'Roave\\DoctrineSimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/roave/doctrine-simplecache/src',
        ),
        'Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'ExceptionalJSON\\' => 
        array (
            0 => __DIR__ . '/..' . '/daverandom/exceptional-json/src',
        ),
        'Doctrine\\Common\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/cache/lib/Doctrine/Common/Cache',
        ),
        'BrowscapPHP\\' => 
        array (
            0 => __DIR__ . '/..' . '/browscap/browscap-php/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit30260c7069db57dc85d078d75ddef1a6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit30260c7069db57dc85d078d75ddef1a6::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
